version: "3.9"

services:
  postgres:
    restart: always
    image: postgres:13.3
    volumes:
      - ./.effective-mobile/postgres/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=interview
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
